# A vantagem de utilizar o arquivo application.yml é pelo fato do arquivo yaml ser estrutura em árvore
# evitando a reescrita de comandos, por exemplo, caso fosse um arquivo application.properties, teríamos:
#
# spring.application.name: API Products
# spring.datasource.url: jdbc:h2:mem:products
#
# Ou seja, teria que escrever a tag raiz spring toda vez

 spring:
  application:
    name: API Products
  datasource:
    url: jdbc:h2:mem:products
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console